version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.5.1
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run:
          name: List files to verify checkout
          command: ls -al
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: npm test audiocapture.test.js
      - run:
          name: Push to integration
          command: |
            git config user.name "UnitTestPipeline-circleci"
            git config user.email "salvationibeh@gmail"
            git checkout -b integration
            git merge develop
            git push origin integration
      - run:
          name: Clean workspace
          command: rm -rf ~/repo/*

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
